apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-memphis-busybox-account
  namespace: {{ include "nats.namespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-memphis-busybox-role
  namespace: {{ include "nats.namespace" . }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["deployments"]
  verbs: ["list", "watch"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list", "watch"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create", "get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-memphis-busybox-role-binding
  namespace: {{ include "nats.namespace" . }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-memphis-busybox-account
  namespace: {{ include "nats.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-memphis-busybox-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: configuration-busybox
  namespace: {{ include "nats.namespace" . }}
spec:
  serviceName: busybox
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
        selector: busybox
    spec:
      terminationGracePeriodSeconds: 30
      serviceAccount: {{ .Release.Name }}-memphis-busybox-account
      containers:
      - name: busybox
        image: memphisos/busybox:4.2
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          value: {{ include "nats.namespace" . }}
