apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-{{ include "nats.namespace" . }}-busybox-account
  namespace: {{ include "nats.namespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-{{ include "nats.namespace" . }}-busybox-role
  namespace: {{ include "nats.namespace" . }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["deployments"]
  verbs: ["list", "watch"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list", "watch"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create", "get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-{{ include "nats.namespace" . }}-busybox-role-binding
  namespace: {{ include "nats.namespace" . }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-{{ include "nats.namespace" . }}-busybox-account
  namespace: {{ include "nats.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-{{ include "nats.namespace" . }}-busybox-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: memphis-busybox
  namespace: {{ include "nats.namespace" . }}
spec:
  template:
    spec:
      serviceAccount: {{ .Release.Name }}-{{ include "nats.namespace" . }}-busybox-account
      containers:
      - name: memphis-busybox
        image: memphisos/k8s-busybox:latest
        imagePullPolicy: Always
        env:
          - name: NAMESPACE
            value: {{ include "nats.namespace" . }}
      restartPolicy: Never
  backoffLimit: 7
  activeDeadlineSeconds: 600